github:
    name:           hiqdev/minii-console

package:
    type:           library
    name:           console
    namespace:      yii\console
    title:          minii Console
    keywords:       minii, console
    description:    |
        [minii](https://github.com/hiqdev/minii-core) is mini version of [Yii2](http://yiiframework.com/), supposed to be fully compatible.
        This package provides console.

require:
    minii/hidev-vendor: "*"
    hiqdev/hidev-php:   "*"
