package:
    type:           library
    name:           minii-console
    namespace:      yii\console
    title:          minii Console
    keywords:       minii, console

composer.json:
    name:           minii/console

require:
    hiqdev/hidev-hiqdev: "*"
    hiqdev/hidev-php:    "*"
